AWSTemplateFormatVersion: "2010-09-09"
Description: Security table for launcher-lock (device keys, nonces, idempotency keys)

Parameters:
  TableName:
    Type: String
    Default: launcher-lock-security
    Description: DynamoDB table name used by Lambda SECURITY_TABLE

Resources:
  SecurityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  SecurityTableName:
    Description: Value for Lambda SECURITY_TABLE environment variable
    Value: !Ref SecurityTable
  SecurityTableArn:
    Description: ARN of the security table
    Value: !GetAtt SecurityTable.Arn
